# Generated by Django 6.0.4 on 2026-06-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("converter", "0008_alter_geofile_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoFile",
            fields=[],
            options={
                "verbose_name": "GeoFile",
                "verbose_name_plural": "GeoFiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("converter.geofile",),
        ),
        migrations.CreateModel(
            name="GeoFileLayer",
            fields=[],
            options={
                "verbose_name": "GeoFileLayer",
                "verbose_name_plural": "GeoFileLayers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("converter.geofilelayer",),
        ),
    ]
