# Generated by Django 6.0.4 on 2026-06-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("converter", "0008_alter_geofile_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("converter.geoprocessingjob",),
        ),
        migrations.CreateModel(
            name="JobLog",
            fields=[],
            options={
                "verbose_name": "Job log",
                "verbose_name_plural": "Job logs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("converter.geoprocessingjoblog",),
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("converter.workflow",),
        ),
    ]
