# Generated by Django 6.0.4 on 2026-06-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("converter", "0008_alter_geofile_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[],
            options={
                "verbose_name": "Audit log",
                "verbose_name_plural": "Audit logs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("converter.auditlog",),
        ),
    ]
