# Generated by Django 6.0.4 on 2026-06-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("converter", "0008_alter_geofile_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinationCredential",
            fields=[],
            options={
                "verbose_name": "Destination credential",
                "verbose_name_plural": "Destination credentials",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("converter.destinationcredential",),
        ),
        migrations.CreateModel(
            name="DispatchedLayer",
            fields=[],
            options={
                "verbose_name": "Dispatched layer",
                "verbose_name_plural": "Dispatched layers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("converter.dispatchedlayer",),
        ),
    ]
