# Generated by Django 4.2.8 on 2026-05-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('error', 'Error')], db_index=True, default='started', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('input_format', models.CharField(blank=True, default='', max_length=64)),
                ('output_format', models.CharField(blank=True, default='', max_length=64)),
                ('crs', models.CharField(blank=True, default='', max_length=64)),
                ('upload_files_count', models.PositiveIntegerField(default=0)),
                ('output_files_count', models.PositiveIntegerField(default=0)),
                ('output_zip_relpath', models.CharField(blank=True, default='', max_length=512)),
                ('download_url', models.CharField(blank=True, default='', max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversionInputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=260)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='converter.conversionjob')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
