# Generated by Django 4.2.8 on 2026-05-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_file_name', models.CharField(blank=True, default='', max_length=260)),
                ('source_kind', models.CharField(blank=True, default='', max_length=16)),
                ('output_format', models.CharField(blank=True, default='', max_length=64)),
                ('geojson_geom', models.TextField(blank=True, default='')),
                ('exported_count', models.PositiveIntegerField(default=0)),
                ('download_url', models.CharField(blank=True, default='', max_length=512)),
                ('output_zip_relpath', models.CharField(blank=True, default='', max_length=512)),
                ('conversion_job_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
