# Generated by Django 5.0.3 on 2026-05-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_locationexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_column='finished_at', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='input_format',
            field=models.CharField(blank=True, db_column='inputformat', default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='output_format',
            field=models.CharField(blank=True, db_column='outputformat', default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('error', 'Error')], db_column='status', db_index=True, default='started', max_length=16),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='task_id',
            field=models.UUIDField(db_column='taskid', db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_column='ipaddress', null=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='query',
            field=models.CharField(db_column='query', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='results_count',
            field=models.PositiveIntegerField(db_column='resultcount', default=0),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True, db_column='searched_at', db_index=True),
        ),
        migrations.AlterModelTable(
            name='conversionjob',
            table='conversion_jobs',
        ),
        migrations.AlterModelTable(
            name='searchlog',
            table='search_logs',
        ),
    ]
