# Generated by Django 5.0.3 on 2026-05-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_uploadquotalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='prj_missing',
            field=models.BooleanField(default=False),
        ),
    ]
