# Generated by Django 5.0.3 on 2026-06-02 05:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_add_database_schema_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchedlayer',
            options={},
        ),
        migrations.RemoveField(
            model_name='destinationcredential',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dispatchedlayer',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='dispatchedlayer',
            name='response_code',
        ),
        migrations.RemoveField(
            model_name='dispatchedlayer',
            name='response_message',
        ),
        migrations.RemoveField(
            model_name='geofilelayer',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='geoprocessingjob',
            name='input_file_id',
        ),
        migrations.RemoveField(
            model_name='geoprocessingjob',
            name='output_file_id',
        ),
        migrations.RemoveField(
            model_name='geoprocessingjob',
            name='worker_id',
        ),
        migrations.RemoveField(
            model_name='geoprocessingjoblog',
            name='job_id',
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='quality_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dispatchedlayer',
            name='job',
            field=models.ForeignKey(blank=True, db_column='job_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='converter.geoprocessingjob'),
        ),
        migrations.AddField(
            model_name='geofilelayer',
            name='file',
            field=models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='converter.geofile'),
        ),
        migrations.AddField(
            model_name='geoprocessingjob',
            name='input_file',
            field=models.ForeignKey(db_column='input_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_jobs', to='converter.geofile'),
        ),
        migrations.AddField(
            model_name='geoprocessingjob',
            name='output_file',
            field=models.ForeignKey(db_column='output_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_jobs', to='converter.geofile'),
        ),
        migrations.AddField(
            model_name='geoprocessingjob',
            name='worker_hostname',
            field=models.CharField(blank=True, db_column='worker_id', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='geoprocessingjoblog',
            name='job',
            field=models.ForeignKey(blank=True, db_column='job_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='converter.geoprocessingjob'),
        ),
        migrations.AlterUniqueTogether(
            name='rbacprincipalrole',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rbacrolepermission',
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name='rbacprincipalrole',
            old_name='role_id',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='rbacprincipalrole',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='converter.rbacrole'),
        ),
        migrations.RenameField(
            model_name='rbacrolepermission',
            old_name='permission_id',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='rbacrolepermission',
            old_name='role_id',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='rbacrolepermission',
            name='permission',
            field=models.ForeignKey(blank=True, db_column='permission_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='converter.rbacpermission'),
        ),
        migrations.AlterField(
            model_name='rbacrolepermission',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='converter.rbacrole'),
        ),
        migrations.AlterUniqueTogether(
            name='rbacprincipalrole',
            unique_together={('principal_id', 'principal_type', 'role', 'org_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rbacrolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='org_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='batchtabledetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='batchtabledetails',
            name='org_id',
            field=models.CharField(blank=True, db_column='org_id', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='destinationcredential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='destinationcredential',
            name='encrypted_secret',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='destinationcredential',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='destinationcredential',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='destinationcredential',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='destinationcredential',
            name='org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinationcredential',
            name='target_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='destinationcredential',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dispatchedlayer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dispatchedlayer',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchedlayer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dispatchedlayer',
            name='org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchedlayer',
            name='payload_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dispatchedlayer',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dispatchedlayer',
            name='target_database_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchedlayer',
            name='target_endpoint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchedlayer',
            name='target_layer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchedlayer',
            name='target_system',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='checksum_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='mime_type',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='original_file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='source_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('remote', 'Remote')], max_length=20),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='source_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='storage_backend',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='storage_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='geofile',
            name='uploaded_by',
            field=models.ForeignKey(db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='geofilelayer',
            name='bbox',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='geofilelayer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='geofilelayer',
            name='encoding',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='geofilelayer',
            name='feature_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='geofilelayer',
            name='fields',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='geofilelayer',
            name='geometry_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='geofilelayer',
            name='has_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geofilelayer',
            name='has_z',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geofilelayer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geofilelayer',
            name='layer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='geofilelayer',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='geofilelayer',
            name='source_crs_epsg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geofilelayer',
            name='source_crs_wkt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='error_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='parameters',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='preview_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='preview_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='priority',
            field=models.CharField(default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='requested_by',
            field=models.ForeignKey(db_column='requested_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='workflow_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='geoprocessingjoblog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True),
        ),
        migrations.AlterField(
            model_name='geoprocessingjoblog',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='geoprocessingjoblog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geoprocessingjoblog',
            name='log_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='geoprocessingjoblog',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='locationexport',
            name='task_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='rbacpermission',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rbacpermission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rbacprincipalrole',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rbacprincipalrole',
            name='org_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='rbacprincipalrole',
            name='principal_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rbacprincipalrole',
            name='principal_type',
            field=models.CharField(choices=[('user', 'User'), ('group', 'Group'), ('org', 'Organization')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rbacrole',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rbacrole',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rbacrole',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rbacrolepermission',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='code',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='destination_type',
            field=models.CharField(choices=[('download', 'Download'), ('feature_mapper', 'Feature Mapper'), ('webhook', 'External Webhook'), ('database', 'External Database')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='parameters_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='preview_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='geoprocessingjob',
            index=models.Index(fields=['status', '-created_at'], name='geo_process_status_b47208_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchedlayer',
            constraint=models.UniqueConstraint(condition=models.Q(('target_layer_id__isnull', False)), fields=('target_system', 'target_layer_id', 'target_database_fingerprint'), name='ux_dispatched_target'),
        ),
        migrations.AddConstraint(
            model_name='geoprocessingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('org_id', 'idempotency_key'), name='ux_jobs_idempotency'),
        ),
    ]
