# Generated by Django 5.0.3 on 2026-06-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_alter_dispatchedlayer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofile',
            name='source_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('remote', 'Remote'), ('local', 'Local')], max_length=20),
        ),
    ]
