# Generated by Django 3.2.25 on 2026-06-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0009_recreate_operator_tables_uuid_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofile',
            name='signature',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geofile',
            name='signature_nonce',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='geofile',
            name='signature_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geoprocessingjob',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='geoprocessingjob',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('running', 'Running'), ('awaiting_preview', 'Awaiting Preview'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partial', 'Partial')], default='created', max_length=20),
        ),
    ]
