# Generated by Django 3.2.25 on 2026-06-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0010_auto_20260629_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geofile',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='geofile',
            name='signature_nonce',
        ),
        migrations.RemoveField(
            model_name='geofile',
            name='signature_timestamp',
        ),
        migrations.AddField(
            model_name='locationexport',
            name='signature',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locationexport',
            name='signature_nonce',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='locationexport',
            name='signature_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
