# Generated by Django 3.2.25 on 2026-06-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0011_auto_20260629_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationexport',
            name='receiver_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locationexport',
            name='signature_verified',
            field=models.BooleanField(default=False),
        ),
    ]
