# Generated by Django 3.2.25 on 2026-06-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0012_auto_20260629_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationexport',
            name='payload_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
