# Generated by Django 5.2.15 on 2026-07-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0013_locationexport_payload_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchedlayer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('confirmed', 'Confirmed'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='geoprocessingjoblog',
            name='log_level',
            field=models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10),
        ),
    ]
